[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/io" = "@stdlib.io.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "system"
    version = "@project.version@"
    path = "../system-native/build/libs/system-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["system"]

    [[platform.libraries]]
    artifactId = "io-native"
    version = "@io.native.version@"
    path = "./lib/io-native-@io.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["system"]

    [[platform.libraries]]
    artifactId = "system"
    version = "@project.version@"
    path = "../system-test-utils/build/libs/system-test-utils-@project.version@.jar"
    groupId = "org.ballerinalang.stdlib.system"
    modules = ["system"]
    scope = "testOnly"
